#pragma once

enum ExitCode {
    WIMPS_SUCCESS = 0,
    WIMPS_FORK_FAILED,
    WIMPS_PTRACE_FAILED,
    WIMPS_EXEC_FAILED,
    WIMPS_MALLOC_FAILED,
    WIMPS_GETCWD_FAILED,
    WIMPS_SIGNAL_FAILED,
    WIMPS_TIMER_CREATE_FAILED,
    WIMPS_TIMER_SET_TIME_FAILED,
    WIMPS_NO_ARGS
};

